[build]
publish = "dist/"
command = "rustup toolchain install nightly && rustup target add wasm32-unknown-unknown && cargo install cargo-leptos --force && cargo leptos serve -r"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[redirects]]
from = "/github"
to = "https://github.com/NiklasEi/leptos-ssg-with-islands"
status = 302
